# 百度贴吧配置
# 是否开启 false 关闭  true 开启
enabled: true
# name任意填 ，bduss 贴吧首页cookie里的BDUSS项目 不会的百度
accounts:
  - name: FGYM
    bduss: GIxSXdPOVkxdFJ0OFNYZGRxT2IzaUFmZWdtQXc1Q0NNWFo0QlhhMmNmeWdndmRqSVFBQUFBJCQAAAAAAAAAAAEAAABG3Gwst-e48dK7w-YxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKD1z2Og9c9ja;
